Create Widget Metabox Group
wpmetabox/mb-elementor-integrator pull request #10
Opened 2022-04-27 03:43 UTC by tuankiet2605

2022-04-30 08:15 UTC, rilwis requested changes

2022-04-30 08:15 UTC, rilwis commented on src/GroupField.php
> +		}
Dùng hàm này hay hơn e nhé: `check_ajax_referer`: https://developer.wordpress.org/reference/functions/check_ajax_referer/, ko phải `die`.

2022-04-30 08:15 UTC, rilwis commented on src/GroupField.php
> +						}
Em viết lại code đoạn này dùng continue và early return để code ngắn gọn nhé. Xem trong KB phần về PHP a có nói đấy.

2022-04-30 08:15 UTC, rilwis commented on src/GroupField.php
> +		$meta_boxs = apply_filters( 'rwmb_meta_boxes', [] );
Nếu chỉ để lấy meta box hoặc lấy các field dạng group thì e nên dùng `rwmb_get_registry`: https://docs.metabox.io/functions/rwmb-get-registry/#field-registry

2022-04-30 08:15 UTC, rilwis commented on src/GroupField.php
> +		if ( isset( $meta_box['fields'] ) ) {
Tuyệt đối tránh những câu lệnh `if` bọc cả đoạn code dài như này. Xem về early return trong KB nhé.

2022-04-30 08:15 UTC, rilwis commented on src/GroupField.php
> +	public static function parse_options( $fields = [], $options = [] ) {
Có lý do nào cho các hàm này đều là static ko em?

2022-04-30 08:15 UTC, rilwis commented on src/GroupField.php
> +				$sub_fields[ $options['id'] . ':' . $field['id'] ] = $field['name'];
Nếu `$option` truyền vào chỉ để lấy `id` của nó thì sao ko truyền trực tiếp `$id` em?

2022-04-30 08:15 UTC, rilwis commented on src/GroupField.php
> +		if ( isset( $fields['fields'] ) && ! empty( $fields['fields'] ) ) {
Dùng early return nhé.

2022-04-30 08:15 UTC, rilwis commented on src/Widgets/LoopGroup.php
> +			'label' => esc_html__( 'Meta Box Field Group', 'mb-elementor-integrator' ),
Đặt tên là Meta Box Group thôi e nhé.

2022-04-30 08:15 UTC, rilwis commented on src/Widgets/LoopGroup.php
> +
Tất cả những options bên dưới này ko dùng làm gì cả, nên em bỏ đi nhé. Ở widget này mình chỉ chọn group nào và skin nào. Ngoài ra thì giữ những option mặc định về style của Elementor thôi.

2022-04-30 08:15 UTC, rilwis commented on src/Widgets/LoopGroup.php
> +				}
Của mình đâu có cần phân trang đâu mà thêm cái này làm gì em? Bỏ đi nhé.

2022-04-30 08:15 UTC, rilwis commented on src/assets/app/controls/mbGroupField.js
> +  return {
Cần gì phải viết kiểu function trả về object em? Sao ko viết trực tiếp là object đi. Hoặc nếu em cần export, import gì thì em viết các hàm cho nó và export cái nào cần.

2022-04-30 08:18 UTC, rilwis commented
Anh mới comment 1 phần trong code của em, nhưng anh thấy 1 vấn đề lớn là em copy & paste quá nhiều, khiến code rất nhiều chỗ thừa (React, pagination, các options của widget), code thì ko format, ko tuân thủ các best practices (early return, JS). Nên a nghĩ việc đầu tiên em cần làm là clean các thứ rối rắm trong code, chỉ giữ lại những thứ thực sự cần thiết để mình làm sáng rõ logic. Sau đó làm thêm cái gì thì làm.

2022-04-30 10:11 UTC, tuankiet2605 commented
Ok, anh. Để em clean code và xử lý những cái anh comment.

2022-05-12 07:41 UTC, rilwis requested changes

2022-05-12 07:41 UTC, rilwis commented on src/Widgets/MBGroup.php
> +		// echo "</pre>"
Xoá code để debug nhé.

2022-05-12 07:41 UTC, rilwis commented on src/Widgets/MBGroup.php
> +		<div class="mbei-loop-group">
Div bao ngoài này anh thấy ko cần thiết, mình xoá bớt đi nhé.

2022-05-12 07:41 UTC, rilwis commented on src/Widgets/Skins/Group_Skin.php
> +class Group_Skin extends Skin_Base {
Anh nghĩ là nên move class này ra ngoài 1 bậc, vì trong thư mục Skins ko có cái gì khác, chỉ có 1 class.

Và đổi tên class thành GroupSkin nhé, ko dùng gạch dưới. Mình theo đúng cách đặt tên của PSR-2 nhé.

2022-05-12 07:41 UTC, rilwis commented on src/Widgets/Skins/Group_Skin.php
> +		$options = [ 0 => 'Select a template' ];
Cho chỗ này dịch được nhé.

2022-05-12 07:41 UTC, rilwis commented on src/Widgets/Skins/Group_Skin.php
> +			);
Câu lệnh này là lấy post ID và post title mà có term = metabox_group_template phải ko? Em xem đổi sang dùng WP_Query cho dễ hiểu được ko?

2022-05-12 07:41 UTC, rilwis commented on src/Widgets/Skins/Group_Skin.php
> +				$data_replace = array_merge( $data_replace, $this->dynamic_tag_to_data( $dynamic_tag, $dynamic_tags_mageger ) );
Chỗ này dùng `continue` để phía dưới khỏi cần else.

2022-05-12 07:41 UTC, rilwis commented on src/Widgets/Skins/Group_Skin.php
> +				. '<div class="mbei-fields mb-columns">';
E xem bỏ bớt 1 cái div bao ngoài đc ko? A thấy ko cần thiết lắm.

2022-05-12 07:41 UTC, rilwis commented on src/GroupField.php
> +		list($post_type, $slug) = explode( '/', $wp_query->query['pagename'] );
Format code nhé.

2022-05-12 07:41 UTC, rilwis commented on src/GroupField.php
> +				$file_type = $type;
Biến `$type` này chưa được khởi tạo.

2022-05-12 07:41 UTC, rilwis commented on src/GroupField.php
> +			if ( 'group' === $field['type'] && isset( $field['clone'] ) && true === $field['clone'] ) {
Như này anh hiểu là mình xử lý cho cloneable group. Vậy với group mà ko cloneable thì có chạy ko e? A test thử thấy chưa chạy.

2022-05-12 07:41 UTC, rilwis commented on src/GroupField.php
> +					}
2 đoạn if..else này sao xử lý giống hệt nhau vậy em? Nếu thế có cần check ko?

2022-05-12 07:41 UTC, rilwis commented on src/ThemeBuilder/Conditions/MBFields.php
> +		return 'Metabox Field';
Em sửa text thành 'Meta Box Field' nhé.

2022-05-12 23:37 UTC, rilwis requested changes

2022-05-12 23:37 UTC, rilwis commented on src/GroupField.php
> +				$file_type = 'text';
Chỗ này a nghĩ viết gọn lại được, khi có `default` là `text` rồi thì các phần case `text`, `textarea`, ... ở trên có thể bỏ được.

2022-05-12 23:37 UTC, rilwis commented on src/Widgets/MBGroup.php
> +			</div>
A thấy các css classnames hơi ko thống nhất. Mình thống nhất đặt là:

- `mbei-groups` bao bên ngoài cùng
- `mbei-group` bao bên trong cho từng item clone của group
- `mbei-subfield mbei-subfield--$key` cho các subfield

E sửa các chỗ khác cũng như thế nhé.

2022-05-13 09:51 UTC, rilwis requested changes

2022-05-13 09:51 UTC, rilwis commented on src/loader.php
> +<?php
Còn 1 tí xíu là đổi tên file thành Loader, chữ L viết hoa e nhé, ko là trên Linux chạy lỗi.

2022-05-13 09:51 UTC, rilwis commented on src/Widgets/Locations/Group.php
> +class Group {
Class này có nên chuyển ra ngoài 1 cấp ko? Đổi tên class thành `GroupLocation` chẳng hạn.

2022-05-21 00:08 UTC, rilwis requested changes

2022-05-21 00:08 UTC, rilwis commented on src/GroupField.php
> +	}
E thử xem hàm này có giống ý tưởng của hàm `Arr::get` của Laravel ko? Nếu đúng thì có thể áp dụng, vì mình đang bê cái `Arr` đó sang Meta Box thông qua package [meta-box/support](https://github.com/wpmetabox/support)

2022-05-21 00:08 UTC, rilwis commented on src/Traits/Post.php
> +				$field_id = str_replace( [ '.' ], [ ':' ], $field['id'] );
Chỗ này chỉ cần viết đơn giản là:

```php
$field_id = str_replace( '.', ':', $field['id'] );
```

2022-05-21 00:08 UTC, rilwis commented on src/Widgets/GroupSkin.php
> +        if( strpos($settings['field-group'], '.') !== false ) {
Format code

2022-05-21 00:08 UTC, rilwis commented on src/Widgets/GroupSkin.php
> +            }
Format code

2022-05-21 00:08 UTC, rilwis commented on src/Widgets/GroupSkin.php
> +                        continue;
Format code, dùng tab thay cho space

2022-05-21 00:08 UTC, rilwis commented on src/Widgets/GroupSkin.php
> +                        }, ARRAY_FILTER_USE_KEY);
Format code

2022-05-21 00:08 UTC, rilwis commented on src/Widgets/GroupSkin.php
> +//                    }
Code cũ mình bỏ đi e nhé, có Git để track rồi

2022-05-23 00:46 UTC, tuankiet2605 commented on src/GroupField.php
> +	}
Hàm này tương tự chứ không giống. Nếu dùng cũng được nhưng phải sửa lại code.

2022-06-23 08:33 UTC, merged